apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: myapp
    type: frontend
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    targetPort: 8080
    port: 80
    nodePort: 30001
  selector:
    app: myapp
    type: frontend 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: myapp
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      type: frontend
  template:
    metadata:
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
      - name: frontend
        image: ernesen/frontend:1.0
        env:
        - name: COMPONENT_BACKEND_HOST
          value: "172.17.0.7"
        - name: COMPONENT_BACKEND_PORT
          value: "8080"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
